title: Kieran Pritchard Portfolio
description: Digital Technology Student Portfolio and Blog
baseurl: "/Kieran-Pritchard-Portfolio"
url: "https://kieranpritchard.github.io"

# Build settings
markdown: kramdown

# Permalink settings (only one permalink setting)
permalink: /:categories/:year/:month/:day/:title.html

# Include files that Jekyll would otherwise ignore
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "res"
  - "Blog-Posts"
  - "src"

# Exclude specific files
exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - .git/
  - .jekyll-cache/
  - node_modules/

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Set default layout for HTML files
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blog_post"
  - scope:
      path: "_portfolio"
      type: "portfolio"
    values:
      layout: "portfolio_post"